vim.g.mapleader  = " "

local keymap = vim.keymap

keymap.set("t", "<Esc>", "<C-\\><C-n>")
keymap.set("i", "jj", "<ESC>:w<cr>")
keymap.set("i", "<ESC>", "<ESC>:w<cr>")
keymap.set("i", "<C-c>", "<ESC>:w<cr>")
keymap.set("i", "<C-f>", "<Right>")
keymap.set("i", "<C-b>", "<Left>")
keymap.set("i", "<C-p>", "<Up>")
keymap.set("i", "<C-n>", "<Down>")
keymap.set("i", "<C-a>", "<C-o>^")
keymap.set("i", "<C-e>", "<C-o>$")

keymap.set("n", "<C-q>", ":q<cr>")
keymap.set("i", "<C-q>", "<ESC>:q<cr>")
keymap.set("t", "<C-q>", "<ESC>:q<cr>")
keymap.set("n", "<leader>h", "^")
keymap.set("n", "<leader>l", "$")
keymap.set("n", "<leader>w", "<C-w>x")
keymap.set("n", "cp", ":Copypath<cr>")
keymap.set("n", "<CR>", "a<Return><Esc>^k")
keymap.set("n", "<leader>no", ":nohl<CR>")
keymap.set("n", "<leader>gr", ":lua print(vim.inspect(vim.treesitter.get_captures_at_cursor(0)))<CR>")
keymap.set("n", "n", "nzz")
keymap.set("n", "N", "Nzz")
keymap.set("n", "*", "*zz")
keymap.set("n", "#", "#zz")
keymap.set("n", "<leader>rp", ":%s/")
keymap.set("v", "<leader>h", "^")
keymap.set("v", "<leader>l", "$")

keymap.set("n", "x", '"_x')
keymap.set("v", "x", '"_x')

keymap.set("n", "<leader>sl", "<C-w>v")
keymap.set("n", "<leader>sj", "<C-w>s")
keymap.set("n", "<leader>sx", ":close<CR>")
keymap.set("n", "<leader>=", "<C-w>15>")
keymap.set("n", "<leader>-", "<C-w>15<")
keymap.set("n", "<leader>m", ":MaximizerToggle<CR>")
keymap.set("n", "<leader>tt", ":NvimTreeToggle<CR>")
keymap.set("n", "<leader>tr", ":NvimTreeRefresh<CR>")
keymap.set("n", "<leader>tx", ":NvimTreeCollapse<CR>")
keymap.set("n","<C-p>", "<cmd>Telescope frecency workspace=CWD<cr>")
keymap.set("n", "<C-f>", "<cmd>lua require('telescope').extensions.live_grep_args.live_grep_args()<CR>")
keymap.set("n", "<leader>fg", "<cmd>Telescope git_bcommits<cr>")
keymap.set("n", "<leader>ft", "<cmd>Telescope<cr>")
keymap.set("n", "<leader>gb", "<cmd>Git blame<cr>")
keymap.set("n", "<leader>te", ":Lspsaga term_toggle<CR>")
keymap.set("n", "gd", "<cmd>Lspsaga peek_definition<CR>")
keymap.set("n", "go", "<cmd>Lspsaga goto_definition<CR>")
keymap.set("n", "rn", "<cmd>Lspsaga rename<CR>")
keymap.set("n", "<leader>dv", ":DiffviewOpen")
keymap.set("n", "<leader>cp", ":Copilot panel<CR>")
