Style/FrozenStringLiteralComment:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false
# new copsを許可(エラーメッセージがうざい)
AllCops:
  NewCops: enable
