Style/FrozenStringLiteralComment:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

# クラスの説明を省くのを許可
Style/Documentation:
  Enabled: false

# ダブルクオーテーションを許可
Style/StringLiterals:
  Enabled: false

# 日本語コメントを許可
Style/AsciiComments:
  Enabled: false

# new copsを許可(エラーメッセージがうざい)
AllCops:
  NewCops: enable
