gui:
  nerdFontsVersion: "3"
git:
  allBranchesLogCmd: git log --graph --oneline --color=always --decorate=full --all
  branchLogCmd: git log --graph --oneline --color=always --decorate=full
  paging:
    colorArg: always
    pager: delta --dark --paging=never
